name: auto-assign-to-project
on:
  issues:
    types:
      - opened

permissions:
  id-token: write # Needed to federate with octo-sts

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: octo-sts/action@6177b4481c00308b3839969c3eca88c96a91775f # v1.0.0
        id: octo-sts
        with:
          scope: ${{ github.repository_owner }}
          identity: org-project
      - uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/orgs/rothandrew-octo-sts-testing/projects/1
          github-token: ${{ steps.octo-sts.outputs.token }}
